<?xml version="1.0" encoding="utf-8"?>
<robot name="bottle_rocket">
  <material name="Red">
    <color rgba="0.8 0.0 0.0 1.0"/>
  </material>

  <property name="length" value="0.26" />
  <property name="wing_span" value="0.8" />
  <property name="radius" value="0.05" />
  <property name="bottle_mass" value="0.5" />
  <property name="fin_mass" value="0.1" />
  <property name="depth" value="0.0001" />
  <property name="PI" value="3.1415926535897931" />

  <macro name="cylinder_inertia" params="m r h">
    <inertia  ixx="${m*(3*r*r+h*h)/12}" ixy = "0.00001" ixz = "0.00001"
              iyy="${m*(3*r*r+h*h)/12}" iyz = "0.00001"
              izz="${m*r*r/2}" /> 
  </macro>

  <macro name="box_inertia" params="m h d w">
    <inertia  ixx="${m*(h*h+d*d)/12}" ixy = "0.00001" ixz = "0.00001"
              iyy="${m*(w*w+d*d)/12}" iyz = "0.00001"
              izz="${m*(w*w+h*h)/12}" /> 
  </macro>

  <!-- <link name="world"/>

  <joint name="fixed" type="fixed">
    <parent link="world"/>
    <child link="bottle"/>
  </joint> -->

  <link name="bottle">
    <inertial>
      <mass value="${bottle_mass}"/>
      <origin xyz="0.00001 0.00001 ${length/2}"/>
      <cylinder_inertia  m="${bottle_mass}" r="${radius}" h="${length}" />
    </inertial>
    <visual>
      <origin rpy="0.00001 0.00001 0.00001" xyz="0.00001 0.00001 ${length/2}"/>
      <geometry>
        <cylinder length="${length}" radius="${radius}"/>
      </geometry>
      <material name="Red"/>
    </visual>
    <collision>
      <origin xyz="0.00001 0.00001 ${length/2}" rpy="0.00001 0.00001 0.00001 " />
      <geometry>

          <cylinder length="${length}" radius="${radius+0.01}" />

      </geometry>
    </collision>   
  </link>
  <gazebo reference="bottle">
    <material>Gazebo/Red</material>
    <turnGravityOff>false</turnGravityOff>
  </gazebo>

   <link name="fin_left">
    <inertial>
    <mass value="${fin_mass}"/>
      <origin xyz="0.00001 ${wing_span/2} 0.00001"/>
      <box_inertia  m="${fin_mass}" d="${length}" w="${depth}" h="${wing_span}" />
    </inertial>
    <visual>
      <origin rpy="0.00001 0.00001 0.00001" xyz="0.00001 ${radius*2}+${wing_span/2} ${length/2}"/>
      <geometry>
        <box size="${depth} ${wing_span} ${length}" />
      </geometry>
      <material name="Red"/>
    </visual>
    <collision>
      <origin xyz="0.00001 ${radius*2}+${wing_span/2} ${length/2}" rpy="0.00001 0.00001 0.00001 " />
      <geometry>

          <box size="${depth} ${wing_span} ${length}" />

      </geometry>
    </collision>   
  </link>

  <gazebo reference="fin_left">
    <material>Gazebo/Red</material>
    <turnGravityOff>false</turnGravityOff>
  </gazebo>

        <gazebo>
    <plugin name="left_fin_lift" filename="libLiftDragPlugin.so">

      <!-- taken from the lift curve figure -->
      <!-- alpha_0 is 5 degrees -->
      <a0>0.08727</a0>
      <!-- alpha_stall is 19.3 degrees -->
      <alpha_stall>0.3368</alpha_stall>
      <!-- slope of the lift curve to the left of the stall angle -->
      <cla>5.418</cla>
      <!-- slope of the lift curve to the right of the stall angle -->
      <cla_stall>-2.1419</cla_stall>

      <cda>0.0001</cda>
      <cda_stall>0.0001</cda_stall>
      <cma>0.0001</cma>
      <cma_stall>0.0001</cma_stall>
      <area>0.418</area>
      <fluid_density>1.225</fluid_density>
      <forward>1 0.001 0.001</forward>
      <upward>-1 0.001 1</upward>
      <cp>0.001 0.425 0.13</cp>
      <link_name>bottle</link_name>
      <radial_symmetry>false</radial_symmetry>
    </plugin>
  </gazebo>



   <joint name="fin_joint_left" type="fixed">
    <parent link="bottle"/>
    <child link="fin_left"/>
  </joint>


  <link name="fin_right">
    <inertial>
    <mass value="${fin_mass}"/>
      <origin xyz="0.00001 ${wing_span/-2} 0.00001"/>
      <box_inertia  m="${fin_mass}" d="${length}" w="${depth}" h="${wing_span}" />
    </inertial>
    <visual>
      <origin rpy="0.00001 0.00001 0.00001" xyz="0.00001 -${radius*2}-${wing_span/2} ${length/2}"/>
      <geometry>
        <box size="${depth} ${wing_span} ${length}" />
      </geometry>
      <material name="Red"/>
    </visual>
    <collision>
      <origin xyz="0.00001 -${radius*2}-${wing_span/2} ${length/2}" rpy="0.00001 0.00001 0.00001 " />
      <geometry>

          <box size="${depth} ${wing_span} ${length}" />

      </geometry>
    </collision>   
  </link>
  <gazebo reference="fin_right">
    <material>Gazebo/Red</material>
    <turnGravityOff>false</turnGravityOff>
  </gazebo>

  <gazebo>
    <plugin name="right_fin_lift" filename="libLiftDragPlugin.so">

          <!-- taken from the lift curve figure -->
          <!-- alpha_0 is 5 degrees -->
          <a0>0.08727</a0>
          <!-- alpha_stall is 19.3 degrees -->
          <alpha_stall>0.3368</alpha_stall>
          <!-- slope of the lift curve to the left of the stall angle -->
          <cla>5.418</cla>
          <!-- slope of the lift curve to the right of the stall angle -->
          <cla_stall>-2.1419</cla_stall>

          <cda>0.0001</cda>
          <cda_stall>0.0001</cda_stall>
          <cma>0.0001</cma>
          <cma_stall>0.0001</cma_stall>
          <area>0.418</area>
          <fluid_density>1.225</fluid_density>
          <forward>1 0.001 0.001</forward>
          <upward>-1 0.001 1</upward>
          <cp>0.001 -0.425 0.13</cp>
          <link_name>bottle</link_name>
          <radial_symmetry>false</radial_symmetry>
        </plugin>
    </gazebo>

   <joint name="fin_joint_right" type="fixed">
    <parent link="bottle"/>
    <child link="fin_right"/>
  </joint>

  

</robot>